feat: update progress
- Make sure run exits successfully if there are no old work flow ID.

This action is to make sure the `clean up` part of the workflow job in CICD is working.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -896,19 +896,36 @@ jobs:
                     --no-paginate --output text)
                     echo OldWorkflowID: "${OldWorkflowID}"
                     echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-                    # Fetch the stack names          
+                    # Fetch the stack names
                     export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
                             --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
                     echo Stack names: "${STACKS[@]}" 
             - run:
                 name: Remove old stacks and files
                 command: |
-                    if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+                    export OldWorkflowID=$(aws cloudformation \
+                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                    --no-paginate --output text)
+                    echo "$OldWorkflowID"
+                    echo "${CIRCLE_WORKFLOW_ID:0:7}"
+                    echo "$OldWorkflowID" ==  "${CIRCLE_WORKFLOW_ID:0:7}";
+                    if [[ "$OldWorkflowID" ==  "${CIRCLE_WORKFLOW_ID:0:7}" ]]
+                    then
+                        echo "OldWorkflowID == CircleCIWorkFlowId. Exiting with success"
+                        exit 0
+                    elif [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
                     then
                         aws s3 rm "s3://image-converter-${OldWorkflowID}" --recursive
+                        echo "after s3"
                         aws cloudformation delete-stack --stack-name image-converter-frontend-${OldWorkflowID}
-                        eksctl delete cluster --name image-converter-${CIRCLE_WORKFLOW_ID:0:7}
+                        echo "after cloud formation"
+                        eksctl delete cluster --name image-converter-${OldWorkflowID}
+                    else
+                        echo "Else condition reached... exiting with error"
+                        exit 1
                     fi
+
+
             - rollback_environment_frontend
             - rollback_environment_kubernetes
             # - notify_slack_error
